name: 릴리즈 생성하기
on:
  push:
    tags:
      - 'v*'

# 권한 설정 추가
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 릴리즈용 ZIP 생성
        run: |
          zip -x "*.git*" "*.github/*" "*.DS_Store" "*.pyc" "__pycache__/*" "*.vscode/*" -r DtoLogFormatter.zip .

      - name: 릴리즈 생성
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: DtoLogFormatter.zip
          name: DtoLogFormatter
          draft: false
          prerelease: false